version: "3.9"
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    volumes:
      - .:/myapp
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - my-network
  # frontend:
  #   build: .
  #   image: chaves/front-busadmin:latest
  #   container_name: frontend
  #   volumes:
  #     - .:/myapp/front-busadmin
  #   command: "yarn start"
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #   - web
  #   networks:
  #     - my-network
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - my-network
networks:
  my-network: