default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: postgres
  password: postgres
  host: localhost
  port: 5432

development:
  <<: *default
  database: busadmin_development

test:
  <<: *default
  database: busadmin_test

production:
  <<: *default
  database: busadmin_production
  username: busadmin
  password: <%= ENV["BUSADMIN_DATABASE_PASSWORD"] %>
