default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: busadmin_web_development
  username: postgres
  password: password
  host: db
  port: 5432

test:
  <<: *default
  database: busadmin_test

production:
  <<: *default
  database: busadmin_production
  username: busadmin
  password: <%= ENV["BUSADMIN_DATABASE_PASSWORD"] %>
